name: Workshop JSON Update

on:
  repository_dispatch:
    types: [update_workshops]

# Prevent concurrent runs from racing each other
concurrency:
  group: workshop-json-updates
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Ensure we're on latest main
        run: |
          git checkout main
          git pull --rebase origin main

      - name: Prepare content file
        id: prep
        run: |
          CONTENT="${{ github.event.client_payload.content_b64 }}"
          # strip CR/LF/spaties en zet URL-safe b64 om
          CONTENT=$(echo "$CONTENT" | tr -d '\r\n ' | tr '_-' '/+')
      
          # Decode en verwijder een extra array-laag als de top een array-van-arrays is
          printf %s "$CONTENT" | base64 -d \
            | jq -c 'if type=="array" and (map(type=="array")|all) then add
                     elif type=="array" and length==1 and (.[0]|type=="array" or type=="object") then .[0]
                     else . end' \
            > tmp.json
      
          FP="${{ github.event.client_payload.filePath }}"
          mkdir -p "$(dirname "$FP")"
          mv tmp.json "$FP"
          echo "FILEPATH=$FP" >> $GITHUB_OUTPUT


      - name: Rebuild workshops index
        run: |
          mkdir -p data/workshops
          # Build a minimal index of all workshops: [{id,title}]
          if ls data/workshops/*.json >/dev/null 2>&1; then
            jq -s '[.[] | {id: .id, title: .title}]' data/workshops/*.json > data/workshops/index.json
          else
            echo "[]" > data/workshops/index.json
          fi

      - name: Commit & push to main with retries
        run: |
          set -e
          git add "${{ steps.prep.outputs.FILEPATH }}" data/workshops/index.json
          git commit -m "${{ github.event.client_payload.commitMessage }}" || echo "No changes to commit"

          # Retry push up to 5 times to survive race conditions
          n=0
          until [ $n -ge 5 ]
          do
            if git push origin main; then
              echo "Pushed successfully"; break
            fi
            echo "Push failed — retrying ($((n+1))/5) after rebase..."
            git pull --rebase --autostash origin main || true
            n=$((n+1))
            sleep 2
          done

          if [ $n -ge 5 ]; then
            echo "ERROR: Could not push after 5 attempts" >&2
            exit 1
          fi
